/**
 * @file This file is part of the Keywork project.
 * @copyright Nirrius, LLC. All rights reserved.
 * @author Teffen Ellis, et al.
 * @license AGPL-3.0
 *
 * @remarks Keywork is free software for non-commercial purposes.
 * You can be released from the requirements of the license by purchasing a commercial license.
 * Buying such a license is mandatory as soon as you develop commercial activities
 * involving the Keywork software without disclosing the source code of your own applications.
 *
 * @see LICENSE.md in the project root for further licensing information.
 */

import fs from 'fs/promises'
import { NPMExportEntry, readNPMPackageJSON } from '@keywork/monorepo/common/imports'
import * as ProjectFiles from '@keywork/monorepo/common/project'
import { CategoryConfig, DocusaurusTypeDoc } from './typedoc.js'
import * as path from 'path'
import TypeDoc from 'typedoc'
import FastGlob from 'fast-glob'
import { titleCase } from 'title-case'

const getDest = (filePath: string) => {
  return path.join(ProjectFiles.DocsAPIDirectory, filePath.substring(ProjectFiles.ModulesDirectory.length))
}

function createFileMap(filePaths: string[]): Map<string, string> {
  return new Map<string, string>(
    filePaths.map((filePath) => {
      return [filePath, getDest(filePath)]
    })
  )
}

async function copyModuleDocs() {
  const ignore = [path.join('**', ProjectFiles.NodeModules)]
  const categoryToDest = await FastGlob(path.join(ProjectFiles.ModulesDirectory, '*', '**', ProjectFiles.Category), {
    ignore,
  }).then(createFileMap)

  const docPathToDest = await FastGlob(path.join(ProjectFiles.ModulesDirectory, '*', '**', '*.{md,mdx}'), {
    ignore,
  }).then(createFileMap)

  await Promise.all(
    [...categoryToDest.values(), ...docPathToDest.values()].map(async (destPath) => {
      await fs.mkdir(path.dirname(destPath), { recursive: true })
    })
  )

  await Promise.all(
    Array.from([...categoryToDest.entries(), ...docPathToDest.entries()], async ([filePath, destPath]) => {
      return fs.copyFile(filePath, destPath)
    })
  )
}

const moduleCategoryConfigs: CategoryConfig[] = []

async function typeDocPlugin(namedExport: string, mapping: NPMExportEntry) {
  const filePath = mapping.import

  const entryPoint = path.join(ProjectFiles.OutDirectory, filePath)
  const outPath = path.join(ProjectFiles.DocsAPIDirectory, path.dirname(filePath))
  await fs.mkdir(outPath, { recursive: true })

  const possibleCategoryPath = path.join(ProjectFiles.ModulesDirectory, path.dirname(filePath), ProjectFiles.Category)
  const categoryContent = await fs.readFile(possibleCategoryPath, 'utf8').catch(() => '')

  const categoryConfig: CategoryConfig = categoryContent ? JSON.parse(categoryContent) : {}

  categoryConfig.dirName ||= path.join('modules', namedExport)
  categoryConfig.name ||= namedExport.split('/').pop() || namedExport
  categoryConfig.label ||= titleCase(categoryConfig.name)
  categoryConfig.collapsible ||= true
  moduleCategoryConfigs.push(categoryConfig)

  const app = new DocusaurusTypeDoc()
  app.bootstrap({
    name: categoryConfig.name,
    entryPoints: [entryPoint],
    githubPages: false,
    excludeInternal: true,
    excludeExternals: true,
    hideGenerator: true,
    cleanOutputDir: false,
    entryDocument: 'api.md',
    readme: 'none',
    hideBreadcrumbs: true,
    hideInPageTOC: true,
  })

  const project = app.convert()!
  project.kind = TypeDoc.ReflectionKind.Module

  await app.generateDocs(project, outPath)
}

const packageJSON = await readNPMPackageJSON(path.join(ProjectFiles.OutDirectory, ProjectFiles.PackageJSON))
const modules = Object.entries(packageJSON.exports).filter(([namedExport]) => !namedExport.endsWith('.json'))

await fs.rm(ProjectFiles.DocsAPIDirectory, { recursive: true, force: true })
await fs.mkdir(ProjectFiles.DocsAPIDirectory, { recursive: true })

for (const [namedExport, exportDeclaration] of modules) {
  await typeDocPlugin(namedExport, exportDeclaration)
}

await copyModuleDocs()

// // This exists to compensate for Docusaurus's lack of index options for autogenerated categories.
// await fs.writeFile(
//   path.join(ProjectFiles.DocsAPIDirectory, 'module-manifest.json'),
//   JSON.stringify(moduleCategoryConfigs, null, 2)
// )
