name: Site Deployment

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build modules
        run: yarn build
        env:
          NODE_ENV: production
          CI: true

      - name: Build site
        run: yarn site:build
        env:
          NODE_ENV: production
          CI: true

      - name: Archive doc site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keywork-site
          path: site/build
          retention-days: 5

      - name: Deploy Site
        if: ${{ env.CLOUDFLARE_API_TOKEN != '' }}
        run: yarn dlx wrangler@latest pages deploy site/build --project-name keywork --branch main
        env:
          NODE_ENV: production
          CI: true
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
