name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build modules
        run: yarn build
        env:
          NODE_ENV: production

      - name: Generate import map
        run: yarn build:importmap

      - name: Run tests
        run: yarn test

      - name: Generate coverage
        run: yarn test:coverage
        continue-on-error: true

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage
        continue-on-error: true

      - name: Build site
        run: yarn site:build
        env:
          NODE_ENV: production

      - name: Archive Keywork artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keywork-dist
          path: dist
          retention-days: 5

      - name: Archive doc site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keywork-site
          path: site/build
          retention-days: 5
